name = "google-workspace"
publisher = "common-fate"
version = "v0.1.2"
language = "python3.9"
[meta]
  icon = "google"
  displayName = "Google Workspace"
  source = "https://github.com/common-fate/cf-provider-google-workspace"